import "../../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationLoader from "../navigationLoader/NavigationLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    <div className="flex w-full items-center justify-center">
      <NavigationLoader />
      <div style={{ width: "640px" }}>{children}</div>
    </div>
    //   </body>
    // </html>
  );
}
